/**
 * DER / PEM parser for RSA keys.
 * Extracts the raw bigint components from SPKI (public) and PKCS#8 (private) PEM strings
 * produced by RsaDer.ts and RsaFromSeed.ts.
 *
 * Supports the exact structures generated by this codebase:
 *   SPKI  → { n, e }
 *   PKCS#8 → { n, e, d, p, q, dp, dq, qInv }
 */

import { bytesToBigInt } from "./RsaMath";

// ── PEM helpers ───────────────────────────────────────────────────────────────

/** Strip PEM headers/footers and base64-decode to raw DER bytes. */
function pemToDer(pem: string): Uint8Array {
  const lines = pem
    .split("\n")
    .filter((l) => !l.startsWith("-----"))
    .join("");
  return Uint8Array.from(Buffer.from(lines, "base64"));
}

// ── Minimal DER reader ────────────────────────────────────────────────────────

class DerReader {
  private pos = 0;

  constructor(private readonly buf: Uint8Array) {}

  private readByte(): number {
    const b = this.buf[this.pos];
    if (b === undefined) throw new Error("DER: unexpected end of input");
    this.pos++;
    return b;
  }

  private readLength(): number {
    const first = this.readByte();
    if (first < 0x80) return first;
    const lenBytes = first & 0x7f;
    let len = 0;
    for (let i = 0; i < lenBytes; i++) len = (len << 8) | this.readByte();
    return len;
  }

  private readTaggedBytes(expectedTag: number): Uint8Array {
    const tag = this.readByte();
    if (tag !== expectedTag)
      throw new Error(`DER: expected tag 0x${expectedTag.toString(16)}, got 0x${tag.toString(16)}`);
    const len = this.readLength();
    const data = this.buf.slice(this.pos, this.pos + len);
    this.pos += len;
    return data;
  }

  /** Read a SEQUENCE (0x30) and return a new reader over its contents. */
  readSequence(): DerReader {
    return new DerReader(this.readTaggedBytes(0x30));
  }

  /** Read an INTEGER (0x02) and return its value as a bigint. */
  readInteger(): bigint {
    const raw = this.readTaggedBytes(0x02);
    // Strip the leading 0x00 sign byte DER adds for positive integers with high bit set.
    const start = raw[0] === 0x00 ? 1 : 0;
    return bytesToBigInt(raw.slice(start));
  }

  /** Read a BIT STRING (0x03), discarding the unused-bits prefix byte. */
  readBitString(): Uint8Array {
    const raw = this.readTaggedBytes(0x03);
    return raw.slice(1); // skip unused-bits byte (always 0x00 for keys)
  }

  /** Read an OCTET STRING (0x04). */
  readOctetString(): Uint8Array {
    return this.readTaggedBytes(0x04);
  }

  /** Skip the next TLV element (used to skip OID + NULL in AlgorithmIdentifier). */
  skip(): void {
    this.readByte(); // tag
    const len = this.readLength();
    this.pos += len;
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

export interface RsaPublicKey {
  n: bigint;
  e: bigint;
}

export interface RsaPrivateKey {
  n: bigint;
  e: bigint;
  d: bigint;
  p: bigint;
  q: bigint;
  dp: bigint;
  dq: bigint;
  qInv: bigint;
}

/**
 * Parse an SPKI PEM public key ("-----BEGIN PUBLIC KEY-----") into {n, e}.
 *
 * DER structure:
 *   SEQUENCE {
 *     SEQUENCE { OID rsaEncryption, NULL }
 *     BIT STRING {
 *       \x00
 *       SEQUENCE { INTEGER n, INTEGER e }
 *     }
 *   }
 */
export function parseSpkiPem(pem: string): RsaPublicKey {
  const outer = new DerReader(pemToDer(pem));
  const outerSeq = outer.readSequence();       // top-level SEQUENCE
  outerSeq.skip();                             // AlgorithmIdentifier SEQUENCE (OID + NULL)
  const inner = new DerReader(outerSeq.readBitString()); // BIT STRING contents
  const keySeq = inner.readSequence();         // RSAPublicKey SEQUENCE
  const n = keySeq.readInteger();
  const e = keySeq.readInteger();
  return { n, e };
}

/**
 * Parse a PKCS#8 PEM private key ("-----BEGIN PRIVATE KEY-----") into full components.
 *
 * DER structure:
 *   SEQUENCE {
 *     INTEGER 0 (version)
 *     SEQUENCE { OID rsaEncryption, NULL }
 *     OCTET STRING {
 *       SEQUENCE {
 *         INTEGER 0, INTEGER n, INTEGER e, INTEGER d,
 *         INTEGER p, INTEGER q, INTEGER dp, INTEGER dq, INTEGER qInv
 *       }
 *     }
 *   }
 */
export function parsePkcs8Pem(pem: string): RsaPrivateKey {
  const outer = new DerReader(pemToDer(pem));
  const outerSeq = outer.readSequence();           // top-level SEQUENCE
  outerSeq.readInteger();                          // version INTEGER (0)
  outerSeq.skip();                                 // AlgorithmIdentifier SEQUENCE
  const inner = new DerReader(outerSeq.readOctetString()); // OCTET STRING contents
  const keySeq = inner.readSequence();             // RSAPrivateKey SEQUENCE
  keySeq.readInteger();                            // version INTEGER (0)
  const n    = keySeq.readInteger();
  const e    = keySeq.readInteger();
  const d    = keySeq.readInteger();
  const p    = keySeq.readInteger();
  const q    = keySeq.readInteger();
  const dp   = keySeq.readInteger();
  const dq   = keySeq.readInteger();
  const qInv = keySeq.readInteger();
  return { n, e, d, p, q, dp, dq, qInv };
}
