/**
 * DER / PEM parser for RSA keys.
 * Mobile port: replaces Buffer.from(lines, "base64") with pure-JS base64ToBytes.
 *
 * Extracts the raw bigint components from SPKI (public) and PKCS#8 (private) PEM strings
 * produced by RsaDer.ts and RsaFromSeed.ts.
 *
 * Supports the exact structures generated by this codebase:
 *   SPKI  → { n, e }
 *   PKCS#8 → { n, e, d, p, q, dp, dq, qInv }
 */

import { bytesToBigInt } from "./RsaMath";
import { base64ToBytes } from "../utils/Bytes";

// ── PEM helpers ───────────────────────────────────────────────────────────────

/** Strip PEM headers/footers and base64-decode to raw DER bytes. */
function pemToDer(pem: string): Uint8Array {
  const lines = pem
    .split("\n")
    .filter((l) => !l.startsWith("-----"))
    .join("");
  // No Buffer — pure-JS base64 decode
  return base64ToBytes(lines);
}

// ── Minimal DER reader ────────────────────────────────────────────────────────

class DerReader {
  private pos = 0;

  constructor(private readonly buf: Uint8Array) {}

  private readByte(): number {
    const b = this.buf[this.pos];
    if (b === undefined) throw new Error("DER: unexpected end of input");
    this.pos++;
    return b;
  }

  private readLength(): number {
    const first = this.readByte();
    if (first < 0x80) return first;
    const lenBytes = first & 0x7f;
    let len = 0;
    for (let i = 0; i < lenBytes; i++) len = (len << 8) | this.readByte();
    return len;
  }

  private readTaggedBytes(expectedTag: number): Uint8Array {
    const tag = this.readByte();
    if (tag !== expectedTag)
      throw new Error(`DER: expected tag 0x${expectedTag.toString(16)}, got 0x${tag.toString(16)}`);
    const len = this.readLength();
    const data = this.buf.slice(this.pos, this.pos + len);
    this.pos += len;
    return data;
  }

  readSequence(): DerReader {
    return new DerReader(this.readTaggedBytes(0x30));
  }

  readInteger(): bigint {
    const raw = this.readTaggedBytes(0x02);
    const start = raw[0] === 0x00 ? 1 : 0;
    return bytesToBigInt(raw.slice(start));
  }

  readBitString(): Uint8Array {
    const raw = this.readTaggedBytes(0x03);
    return raw.slice(1);
  }

  readOctetString(): Uint8Array {
    return this.readTaggedBytes(0x04);
  }

  skip(): void {
    this.readByte();
    const len = this.readLength();
    this.pos += len;
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

export interface RsaPublicKey {
  n: bigint;
  e: bigint;
}

export interface RsaPrivateKey {
  n: bigint;
  e: bigint;
  d: bigint;
  p: bigint;
  q: bigint;
  dp: bigint;
  dq: bigint;
  qInv: bigint;
}

export function parseSpkiPem(pem: string): RsaPublicKey {
  const outer = new DerReader(pemToDer(pem));
  const outerSeq = outer.readSequence();
  outerSeq.skip();
  const inner = new DerReader(outerSeq.readBitString());
  const keySeq = inner.readSequence();
  const n = keySeq.readInteger();
  const e = keySeq.readInteger();
  return { n, e };
}

export function parsePkcs8Pem(pem: string): RsaPrivateKey {
  const outer = new DerReader(pemToDer(pem));
  const outerSeq = outer.readSequence();
  outerSeq.readInteger();
  outerSeq.skip();
  const inner = new DerReader(outerSeq.readOctetString());
  const keySeq = inner.readSequence();
  keySeq.readInteger();
  const n    = keySeq.readInteger();
  const e    = keySeq.readInteger();
  const d    = keySeq.readInteger();
  const p    = keySeq.readInteger();
  const q    = keySeq.readInteger();
  const dp   = keySeq.readInteger();
  const dq   = keySeq.readInteger();
  const qInv = keySeq.readInteger();
  return { n, e, d, p, q, dp, dq, qInv };
}
